name: Docker build

on:
  push:
    branches:
      - master
  release:
    types:
      - released

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    #- name: Set up Docker Buildx
    #  id: buildx
    #  uses: crazy-max/ghaction-docker-buildx@v3
    #  with:
    #    buildx-version: latest
    #    qemu-version: latest

    - name: Build
      run: make docker

    - name: Docker login
      run: make docker-login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: make push-edge

    - name: Set version
      if: "startsWith(github.ref, 'refs/tags/v')"
      env:
        REF: ${{ github.ref }}
      run: echo "::set-env name=VERSION::$(echo $REF | sed 's:refs/tags/v::' )"

    - name: Push images
      if: "startsWith(github.ref, 'refs/tags/v')"
      run: make push-release
