name: Docker build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    #- name: Set up Docker Buildx
    #  id: buildx
    #  uses: crazy-max/ghaction-docker-buildx@v3
    #  with:
    #    buildx-version: latest
    #    qemu-version: latest

    - name: Build
      run: make docker

    - name: Docker login
      run: make docker-login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    - name: Push egde images
      if: "!startsWith(github.ref, 'refs/tags/')"
      run: make push-edge

    - name: Push images
      if: "startsWith(github.ref, 'refs/tags/')"
      run: make push-release
